#!/usr/bin/env bash

echo "== delete-objects"

# check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-objects \
    --bucket $BUCKET_NAME