#!/usr/bin/env bash

echo "== put-object"

# check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

# check for file name
if [ -z "$2" ]; then
    echo "No file name provided."
    exit 1
fi

BUCKET_NAME="$1"
FILE_BODY="$2"
OBJECT_KEY=$(basename, "$FILE_BODY")

aws s3api put-object \
    --bucket "$BUCKET_NAME" \
    --key "$OBJECT_KEY" \
    --body "$FILE_BODY"